option(ENABLE_SANITIZE "enable address sanitize" OFF)
if(ENABLE_SANITIZE)
  add_compile_options("-fno-omit-frame-pointer")
  add_compile_options("-fno-optimize-sibling-calls")
  add_compile_options("-fsanitize=address")
  add_compile_options("-fsanitize-address-use-after-scope")

  add_link_options("-fno-omit-frame-pointer")
  add_link_options("-fno-optimize-sibling-calls")
  add_link_options("-fsanitize=address")
endif()

option(ENABLE_SANITIZE_THREAD "enable thread sanitize" OFF)
if(ENABLE_SANITIZE_THREAD)
  add_compile_options("-fno-omit-frame-pointer")
  add_compile_options("-fno-optimize-sibling-calls")
  add_compile_options("-fsanitize=thread")
  add_compile_options("-fsanitize-address-use-after-scope")

  add_link_options("-fno-omit-frame-pointer")
  add_link_options("-fno-optimize-sibling-calls")
  add_link_options("-fsanitize=thread")
endif()

option(ENABLE_SANITIZE_THREAD "enable memory sanitize" OFF)
if(ENABLE_SANITIZE_THREAD)
  add_compile_options("-fno-omit-frame-pointer")
  add_compile_options("-fno-optimize-sibling-calls")
  add_compile_options("-fsanitize=memory")
  add_compile_options("-fsanitize-memory-track-origins")

  add_link_options("-fno-omit-frame-pointer")
  add_link_options("-fno-optimize-sibling-calls")
  add_link_options("-fsanitize=memory")
  add_link_options("-fsanitize-memory-track-origins")
endif()

option(ENABLE_SANITIZE_THREAD "enable thread sanitize" OFF)
if(ENABLE_SANITIZE_THREAD)
  add_compile_options("-fno-omit-frame-pointer")
  add_compile_options("-fsanitize=undefined")

  add_link_options("-fno-omit-frame-pointer")
  add_link_options("-fsanitize=undefined")
endif()
