name: build

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal --component clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test --verbose

  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe: ccargo
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            exe: ccargo.exe
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            exe: ccargo
            target: x86_64-apple-darwin
          - os: macos-latest
            exe: ccargo
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
