name: Release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Cross build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            exe: majora
            cross: false

          - os: macos-latest
            target: x86_64-apple-darwin
            exe: majora
            cross: false

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe: majora.exe
            cross: false

          - os: windows-latest
            target: i686-pc-windows-msvc
            exe: majora.exe
            cross: false

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe: majora
            cross: false

          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            exe: majora
            cross: false

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            exe: majora
            cross: false

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal

      # Native build
      - name: Install target
        if: matrix.cross == false
        run: rustup target add ${{ matrix.target }}
      - name: Run tests
        if: matrix.cross == false && matrix.target != 'aarch64-apple-darwin'
        run: cargo test --release --target ${{ matrix.target }} --verbose
      - name: Build release
        if: matrix.cross == false
        run: cargo build --release --target ${{ matrix.target }}

      # Cross build
      - name: Install cross
        if: matrix.cross
        run: cargo install --version 0.2.5 cross
      - name: Run tests
        if: matrix.cross
        run: cross test --release --target ${{ matrix.target }} --verbose
      - name: Build release
        if: matrix.cross
        run: cross build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: majora-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.exe }}

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: majora-${{ matrix.target }}.zip
          directory: target/${{ matrix.target }}/release/
          path: ${{ matrix.exe }}

      - name: Publish
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/majora-${{ matrix.target }}.zip
          generate_release_notes: true
          draft: true
